---
# ✅ PLAY 1: Fetch ServiceNow Data
- name: Fetch ServiceNow Data
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../vars/vars.yml

  tasks:
    - include_tasks: ../tasks/fetch_servicenow.yml


# ✅ PLAY 2: Create AMI
- name: Create AMI
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Generate unique AMI name
      set_fact:
        final_ami_name: "{{ ami_name }}-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"

    - name: Create AMI
      amazon.aws.ec2_ami:
        instance_id: "{{ instance_id }}"
        name: "{{ final_ami_name }}"
        region: "{{ region }}"
        wait: yes
        no_reboot: "{{ reboot_flag == 'false' }}"
      register: ami_output
      ignore_errors: true

    - name: Extract AMI ID
      set_fact:
        ami_id: "{{ ami_output.image_id }}"
      when: ami_output.failed is not defined or not ami_output.failed

    - name: Set Status
      set_fact:
        ami_status: "{{ 'success' if (ami_output.failed is not defined or not ami_output.failed) else 'failed' }}"

    - name: Show AWS full error
      debug:
        var: ami_output

    - name: Debug output
      debug:
        msg:
          - "AMI Name: {{ final_ami_name }}"
          - "Status: {{ ami_status }}"
          - "AMI ID: {{ ami_id | default('N/A') }}"


# ✅ PLAY 3: Update ServiceNow
- name: Update ServiceNow
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../vars/vars.yml

  tasks:
    - include_tasks: ../tasks/update_servicenow.yml
